start = 900
software = "msdos622"
chd = "import_dev_hdd_1G"
keymap = "ms_naturl"
machine = "at486"

tags = {                                                                        
  screen1 = ":isa1:svga_et4k:screen",                                           
  flop1 = ":board1:fdcsmc:fdc:0:35hd",                                          
  flop2 = ":board1:fdcsmc:fdc:1:35hd",                                          
  hard1 = ":board3:ide:ide:0:hdd:image",                                        
  cdrom1 = ":board3:ide:ide:1:cdrom:image",                                     
}   

  -- offset, release delay, portmap, comment
t_software = {
  -- MSDOS 622
  { 0, 5, "KEYCODE_F1", "" },
  { 97, 5, "KEYCODE_ENTER", "" },
  { 52, 5, "KEYCODE_DOWN", "" },
  { 27, 5, "KEYCODE_DOWN", "" },
  { 19, 5, "KEYCODE_DOWN", "" },
  { 14, 5, "KEYCODE_DOWN", "" },
  { 13, 5, "KEYCODE_DOWN", "" },
  { 13, 5, "KEYCODE_DOWN", "" },
  { 15, 5, "KEYCODE_DOWN", "" },
  { 21, 5, "KEYCODE_DOWN", "" },
  { 67, 5, "KEYCODE_PGUP", "" },
  { 106, 5, "KEYCODE_2", "" },
  { 18, 5, "KEYCODE_0", "" },
  { 31, 5, "KEYCODE_4", "" },
  { 23, 5, "KEYCODE_8", "" },
  { 29, 5, "KEYCODE_ENTER", "" },
  { 30, 5, "KEYCODE_1", "" },
  { 37, 5, "KEYCODE_6", "" },
  { 20, 5, "KEYCODE_ENTER", "" },
  { 20, 5, "KEYCODE_ENTER", "" },
  { 20, 5, "KEYCODE_ENTER", "" },
  { 114, 5, "KEYCODE_6", "" },
  { 52, 5, "KEYCODE_3", "" },
  { 21, 5, "KEYCODE_ENTER", "" },
  { 65, 5, "KEYCODE_DOWN", "" },
  { 75, 5, "KEYCODE_PGDN", "" },
  { 53, 5, "KEYCODE_PGUP", "" },
  { 19, 5, "KEYCODE_PGUP", "" },
  { 45, 5, "KEYCODE_DOWN", "" },
  { 28, 5, "KEYCODE_PGUP", "" },
  { 126, 5, "KEYCODE_ESC", "" },
  { 28, 5, "KEYCODE_DOWN", "" },
  { 29, 5, "KEYCODE_ENTER", "" },
  { 31, 5, "KEYCODE_DOWN", "" },
  { 24, 5, "KEYCODE_DOWN", "" },
  { 34, 5, "KEYCODE_DOWN", "" },
  { 19, 5, "KEYCODE_DOWN", "" },
  { 15, 5, "KEYCODE_DOWN", "" },
  { 15, 5, "KEYCODE_DOWN", "" },
  { 15, 5, "KEYCODE_DOWN", "" },
  { 15, 5, "KEYCODE_DOWN", "" },
  { 16, 5, "KEYCODE_DOWN", "" },
  { 17, 5, "KEYCODE_DOWN", "" },
  { 19, 5, "KEYCODE_DOWN", "" },
  { 18, 5, "KEYCODE_DOWN", "" },
  { 24, 5, "KEYCODE_DOWN", "" },
  { 54, 5, "KEYCODE_PGUP", "" },
  { 136, 5, "KEYCODE_ESC", "" },
  { 43, 5, "KEYCODE_DOWN", "" },
  { 21, 5, "KEYCODE_DOWN", "" },
  { 19, 5, "KEYCODE_DOWN", "" },
  { 19, 5, "KEYCODE_DOWN", "" },
  { 23, 5, "KEYCODE_DOWN", "" },
  { 24, 5, "KEYCODE_ENTER", "" },
  { 62, 5, "KEYCODE_Y", "" },
  { 57, 5, "KEYCODE_ENTER", "" },
  { 10, 10, "attach_flop1_flop1", "Insert Floppy Disk 1" },
  { 2737, 5, "KEYCODE_ENTER", "" },
  { 98, 5, "KEYCODE_ENTER", "" },
  { 224, 5, "KEYCODE_ENTER", "" },
  { 2871, 5, "KEYCODE_ENTER", "" },
  { 91, 5, "KEYCODE_ENTER", "" },
  { 6518, 5, "attach_flop1_flop2", "Insert Floppy Disk 2" },
  { 83, 5, "KEYCODE_ENTER", "" },
  { 10100, 5, "attach_flop1_flop3", "Insert Floppy Disk 3" },
  { 60, 5, "KEYCODE_ENTER", "" },
  { 8618, 5, "eject_flop1", "Empty Floppy Disk Drive" },
  { 125, 5, "KEYCODE_ENTER", "" },
  { 100, 5, "KEYCODE_ENTER", "" },
  { 3000, 10, "throttle", "Throttle" },
}
