portmap = {
	-- :cia_0_port_a
	["KEYCODE_A"] = { ":cia_0_port_a", "P2 Button 1" },
	["MOUSECODE_2_UNKNOWN_SWITCH"] = { ":cia_0_port_a", "P2 Button 1" },
	["GUNCODE_2_UNKNOWN_SWITCH"] = { ":cia_0_port_a", "P2 Button 1" },
	["KEYCODE_LCONTROL"] = { ":cia_0_port_a", "P1 Button 1" },
	["MOUSECODE_1_BUTTON1"] = { ":cia_0_port_a", "P1 Button 1" },
	["GUNCODE_1_BUTTON1"] = { ":cia_0_port_a", "P1 Button 1" },
	["JOYCODE_1_BUTTON1"] = { ":cia_0_port_a", "P1 Button 1" },
	-- :input
	-- :joy_0_dat
	-- :joy_1_dat
	-- :kbd:a500_us:COLS
	-- :kbd:a500_us:META
	["KEYCODE_RSHIFT"] = { ":kbd:a500_us:META", "Right Shift" },
	["KEYCODE_LSHIFT"] = { ":kbd:a500_us:META", "Left Shift" },
	["KEYCODE_LWIN"] = { ":kbd:a500_us:META", "Left Amiga" },
	["KEYCODE_LALT"] = { ":kbd:a500_us:META", "Left Alt" },
	["KEYCODE_RWIN"] = { ":kbd:a500_us:META", "Right Amiga" },
	["KEYCODE_LCONTROL"] = { ":kbd:a500_us:META", "Ctrl" },
	["KEYCODE_RALT"] = { ":kbd:a500_us:META", "Right Alt" },
	-- :kbd:a500_us:ROW0
	["KEYCODE_ASTERISK"] = { ":kbd:a500_us:ROW0", "Keypad *" },
	["KEYCODE_CAPSLOCK"] = { ":kbd:a500_us:ROW0", "Caps Lock" },
	["KEYCODE_TILDE"] = { ":kbd:a500_us:ROW0", "`  ~" },
	["KEYCODE_ESC"] = { ":kbd:a500_us:ROW0", "Esc" },
	["KEYCODE_TAB"] = { ":kbd:a500_us:ROW0", "Tab" },
	-- :kbd:a500_us:ROW1
	["KEYCODE_Z"] = { ":kbd:a500_us:ROW1", "z  Z  ± ¬" },
	["KEYCODE_PLUSPAD"] = { ":kbd:a500_us:ROW1", "Keypad +" },
	["KEYCODE_1"] = { ":kbd:a500_us:ROW1", "1  !  ¹" },
	["KEYCODE_A"] = { ":kbd:a500_us:ROW1", "a  A  æ Æ" },
	["KEYCODE_NUMLOCK"] = { ":kbd:a500_us:ROW1", "Keypad (" },
	["KEYCODE_Q"] = { ":kbd:a500_us:ROW1", "q  Q  å Å" },
	-- :kbd:a500_us:ROW10
	["KEYCODE_COLON"] = { ":kbd:a500_us:ROW10", ";  :" },
	["KEYCODE_7PAD"] = { ":kbd:a500_us:ROW10", "Keypad 7" },
	["KEYCODE_F7"] = { ":kbd:a500_us:ROW10", "F7" },
	["KEYCODE_P"] = { ":kbd:a500_us:ROW10", "p  P  ¶" },
	["KEYCODE_0"] = { ":kbd:a500_us:ROW10", "0  )  »" },
	["KEYCODE_SLASH"] = { ":kbd:a500_us:ROW10", "/  ?" },
	-- :kbd:a500_us:ROW11
	["KEYCODE_4PAD"] = { ":kbd:a500_us:ROW11", "Keypad 4" },
	["KEYCODE_QUOTE"] = { ":kbd:a500_us:ROW11", "'  \"" },
	["KEYCODE_MINUS"] = { ":kbd:a500_us:ROW11", "-  _" },
	["KEYCODE_F8"] = { ":kbd:a500_us:ROW11", "F8" },
	["KEYCODE_OPENBRACE"] = { ":kbd:a500_us:ROW11", "[  {" },
	-- :kbd:a500_us:ROW12
	["KEYCODE_1PAD"] = { ":kbd:a500_us:ROW12", "Keypad 1" },
	["KEYCODE_F9"] = { ":kbd:a500_us:ROW12", "F9" },
	["KEYCODE_CLOSEBRACE"] = { ":kbd:a500_us:ROW12", "]  }" },
	["KEYCODE_EQUALS"] = { ":kbd:a500_us:ROW12", "=  +" },
	["KEYCODE_SPACE"] = { ":kbd:a500_us:ROW12", "Space" },
	-- :kbd:a500_us:ROW13
	["KEYCODE_F10"] = { ":kbd:a500_us:ROW13", "F10" },
	["KEYCODE_DEL"] = { ":kbd:a500_us:ROW13", "Delete" },
	["KEYCODE_0PAD"] = { ":kbd:a500_us:ROW13", "Keypad 0" },
	["KEYCODE_BACKSPACE"] = { ":kbd:a500_us:ROW13", "Backspace" },
	["KEYCODE_ENTER"] = { ":kbd:a500_us:ROW13", "Enter" },
	["KEYCODE_BACKSLASH"] = { ":kbd:a500_us:ROW13", "\  |" },
	-- :kbd:a500_us:ROW14
	["KEYCODE_INSERT"] = { ":kbd:a500_us:ROW14", "Help" },
	["KEYCODE_MINUSPAD"] = { ":kbd:a500_us:ROW14", "Keypad -" },
	["KEYCODE_RIGHT"] = { ":kbd:a500_us:ROW14", "Cursor Right" },
	["KEYCODE_UP"] = { ":kbd:a500_us:ROW14", "Cursor Up" },
	["KEYCODE_DOWN"] = { ":kbd:a500_us:ROW14", "Cursor Down" },
	["KEYCODE_LEFT"] = { ":kbd:a500_us:ROW14", "Cursor Left" },
	-- :kbd:a500_us:ROW2
	["KEYCODE_S"] = { ":kbd:a500_us:ROW2", "s  S  ß §" },
	["KEYCODE_2"] = { ":kbd:a500_us:ROW2", "2  @  ²" },
	["KEYCODE_W"] = { ":kbd:a500_us:ROW2", "w  W  °" },
	["KEYCODE_X"] = { ":kbd:a500_us:ROW2", "x  X  × ÷" },
	["KEYCODE_F1"] = { ":kbd:a500_us:ROW2", "F1" },
	["KEYCODE_9PAD"] = { ":kbd:a500_us:ROW2", "Keypad 9" },
	-- :kbd:a500_us:ROW3
	["KEYCODE_6PAD"] = { ":kbd:a500_us:ROW3", "Keypad 6" },
	["KEYCODE_3"] = { ":kbd:a500_us:ROW3", "3  #  ³" },
	["KEYCODE_C"] = { ":kbd:a500_us:ROW3", "c  C  ç Ç" },
	["KEYCODE_D"] = { ":kbd:a500_us:ROW3", "d  D  ð Ð" },
	["KEYCODE_F2"] = { ":kbd:a500_us:ROW3", "F2" },
	["KEYCODE_E"] = { ":kbd:a500_us:ROW3", "e  E  ©" },
	-- :kbd:a500_us:ROW4
	["KEYCODE_R"] = { ":kbd:a500_us:ROW4", "r  R  ®" },
	["KEYCODE_F"] = { ":kbd:a500_us:ROW4", "f  F  ´" },
	["KEYCODE_F3"] = { ":kbd:a500_us:ROW4", "F3" },
	["KEYCODE_V"] = { ":kbd:a500_us:ROW4", "v  V  ª" },
	["KEYCODE_3PAD"] = { ":kbd:a500_us:ROW4", "Keypad 3" },
	["KEYCODE_4"] = { ":kbd:a500_us:ROW4", "4  $  ¢" },
	-- :kbd:a500_us:ROW5
	["KEYCODE_F4"] = { ":kbd:a500_us:ROW5", "F4" },
	["KEYCODE_T"] = { ":kbd:a500_us:ROW5", "t  T  þ Þ" },
	["KEYCODE_B"] = { ":kbd:a500_us:ROW5", "b  B  º" },
	["KEYCODE_5"] = { ":kbd:a500_us:ROW5", "5  %  ¼" },
	["KEYCODE_DELPAD"] = { ":kbd:a500_us:ROW5", "Keypad ." },
	["KEYCODE_G"] = { ":kbd:a500_us:ROW5", "g  G  ˋ" },
	-- :kbd:a500_us:ROW6
	["KEYCODE_F5"] = { ":kbd:a500_us:ROW6", "F5" },
	["KEYCODE_6"] = { ":kbd:a500_us:ROW6", "6  ^  ½" },
	["KEYCODE_H"] = { ":kbd:a500_us:ROW6", "h  H  ˆ" },
	["KEYCODE_Y"] = { ":kbd:a500_us:ROW6", "y  Y  ¤ ¥" },
	["KEYCODE_8PAD"] = { ":kbd:a500_us:ROW6", "Keypad 8" },
	["KEYCODE_N"] = { ":kbd:a500_us:ROW6", "n  N  ­ ¯" },
	-- :kbd:a500_us:ROW7
	["KEYCODE_5PAD"] = { ":kbd:a500_us:ROW7", "Keypad 5" },
	["KEYCODE_J"] = { ":kbd:a500_us:ROW7", "j  J  ˜" },
	["KEYCODE_7"] = { ":kbd:a500_us:ROW7", "7  &  ¾" },
	["KEYCODE_SCRLOCK"] = { ":kbd:a500_us:ROW7", "Keypad )" },
	["KEYCODE_U"] = { ":kbd:a500_us:ROW7", "u  U  µ" },
	["KEYCODE_M"] = { ":kbd:a500_us:ROW7", "m  M  ¸ ¿" },
	-- :kbd:a500_us:ROW8
	["KEYCODE_COMMA"] = { ":kbd:a500_us:ROW8", ",  <" },
	["KEYCODE_8"] = { ":kbd:a500_us:ROW8", "8  *  ·" },
	["KEYCODE_F6"] = { ":kbd:a500_us:ROW8", "F6" },
	["KEYCODE_K"] = { ":kbd:a500_us:ROW8", "k  K  ¨" },
	["KEYCODE_I"] = { ":kbd:a500_us:ROW8", "i  I  ¡ ¦" },
	["KEYCODE_2PAD"] = { ":kbd:a500_us:ROW8", "Keypad 2" },
	-- :kbd:a500_us:ROW9
	["KEYCODE_STOP"] = { ":kbd:a500_us:ROW9", ".  >" },
	["KEYCODE_O"] = { ":kbd:a500_us:ROW9", "o  O  ø Ø" },
	["KEYCODE_ENTERPAD"] = { ":kbd:a500_us:ROW9", "Keypad Enter" },
	["KEYCODE_9"] = { ":kbd:a500_us:ROW9", "9  (  «" },
	["KEYCODE_L"] = { ":kbd:a500_us:ROW9", "l  L  £" },
	["KEYCODE_SLASHPAD"] = { ":kbd:a500_us:ROW9", "Keypad /" },
	-- :p1_joy
	["KEYCODE_UP"] = { ":p1_joy", "P1 Up" },
	["JOYCODE_1_YAXIS_UP_SWITCH"] = { ":p1_joy", "P1 Up" },
	["JOYCODE_1_HAT1UP"] = { ":p1_joy", "P1 Up" },
	["KEYCODE_RIGHT"] = { ":p1_joy", "P1 Right" },
	["JOYCODE_1_XAXIS_RIGHT_SWITCH"] = { ":p1_joy", "P1 Right" },
	["JOYCODE_1_HAT1RIGHT"] = { ":p1_joy", "P1 Right" },
	["KEYCODE_LEFT"] = { ":p1_joy", "P1 Left" },
	["JOYCODE_1_XAXIS_LEFT_SWITCH"] = { ":p1_joy", "P1 Left" },
	["JOYCODE_1_HAT1LEFT"] = { ":p1_joy", "P1 Left" },
	["KEYCODE_DOWN"] = { ":p1_joy", "P1 Down" },
	["JOYCODE_1_YAXIS_DOWN_SWITCH"] = { ":p1_joy", "P1 Down" },
	["JOYCODE_1_HAT1DOWN"] = { ":p1_joy", "P1 Down" },
	-- :p1_mouse_x
	["MOUSECODE_1_XAXIS"] = { ":p1_mouse_x", "Mouse X" },
	-- :p1_mouse_y
	["MOUSECODE_1_YAXIS"] = { ":p1_mouse_y", "Mouse Y" },
	-- :p2_joy
	["KEYCODE_G"] = { ":p2_joy", "P2 Right" },
	["KEYCODE_D"] = { ":p2_joy", "P2 Left" },
	["KEYCODE_R"] = { ":p2_joy", "P2 Up" },
	["KEYCODE_F"] = { ":p2_joy", "P2 Down" },
	-- :p2_mouse_x
	["MOUSECODE_2_UNKNOWN_RELATIVE"] = { ":p2_mouse_x", "Mouse X 2" },
	-- :p2_mouse_y
	["MOUSECODE_2_UNKNOWN_RELATIVE"] = { ":p2_mouse_y", "Mouse Y 2" },
	-- :potgo
	["KEYCODE_S"] = { ":potgo", "P2 Button 2" },
	["MOUSECODE_2_UNKNOWN_SWITCH"] = { ":potgo", "P2 Button 2" },
	["GUNCODE_2_UNKNOWN_SWITCH"] = { ":potgo", "P2 Button 2" },
	["KEYCODE_LALT"] = { ":potgo", "P1 Button 2" },
	["MOUSECODE_1_BUTTON3"] = { ":potgo", "P1 Button 2" },
	["GUNCODE_1_BUTTON2"] = { ":potgo", "P1 Button 2" },
	["JOYCODE_1_BUTTON2"] = { ":potgo", "P1 Button 2" },
	["KEYCODE_SPACE"] = { ":potgo", "P1 Button 3" },
	["MOUSECODE_1_BUTTON2"] = { ":potgo", "P1 Button 3" },
	["JOYCODE_1_BUTTON3"] = { ":potgo", "P1 Button 3" },
	["KEYCODE_Q"] = { ":potgo", "P2 Button 3" },
	["MOUSECODE_2_UNKNOWN_SWITCH"] = { ":potgo", "P2 Button 3" },
}

