portmap = {
	-- :board4:fdc37c93x:at_keyboard:pc_keyboard_0
	["KEYCODE_EQUALS"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "= +" },
	["KEYCODE_3"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "3 #" },
	["KEYCODE_ESC"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "Esc" },
	["KEYCODE_5"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "5 %" },
	["KEYCODE_BACKSPACE"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "<--" },
	["KEYCODE_1"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "1 !" },
	["KEYCODE_TAB"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "Tab" },
	["KEYCODE_2"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "2 @" },
	["KEYCODE_MINUS"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "- _" },
	["KEYCODE_0"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "0 )" },
	["KEYCODE_9"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "9 (" },
	["KEYCODE_4"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "4 $" },
	["KEYCODE_7"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "7 &" },
	["KEYCODE_8"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "8 *" },
	["KEYCODE_6"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_0", "6 ^" },
	-- :board4:fdc37c93x:at_keyboard:pc_keyboard_1
	["KEYCODE_S"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "S" },
	["KEYCODE_R"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "R" },
	["KEYCODE_Q"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "Q" },
	["KEYCODE_P"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "P" },
	["KEYCODE_W"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "W" },
	["KEYCODE_A"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "A" },
	["KEYCODE_U"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "U" },
	["KEYCODE_T"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "T" },
	["KEYCODE_LCONTROL"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "L-Ctrl" },
	["KEYCODE_ENTER"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "Enter" },
	["KEYCODE_I"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "I" },
	["KEYCODE_CLOSEBRACE"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "] }" },
	["KEYCODE_O"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "O" },
	["KEYCODE_OPENBRACE"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "[ {" },
	["KEYCODE_E"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "E" },
	["KEYCODE_Y"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_1", "Y" },
	-- :board4:fdc37c93x:at_keyboard:pc_keyboard_2
	["KEYCODE_C"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "C" },
	["KEYCODE_V"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "V" },
	["KEYCODE_X"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "X" },
	["KEYCODE_Z"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "Z" },
	["KEYCODE_G"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "G" },
	["KEYCODE_F"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "F" },
	["KEYCODE_BACKSLASH"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "\\ |" },
	["KEYCODE_D"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "D" },
	["KEYCODE_K"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "K" },
	["KEYCODE_J"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "J" },
	["KEYCODE_LSHIFT"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "L-Shift" },
	["KEYCODE_H"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "H" },
	["KEYCODE_TILDE"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "` ~" },
	["KEYCODE_QUOTE"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "\' \"" },
	["KEYCODE_COLON"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "; :" },
	["KEYCODE_L"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_2", "L" },
	-- :board4:fdc37c93x:at_keyboard:pc_keyboard_3
	["KEYCODE_F5"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "F5" },
	["KEYCODE_B"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "B" },
	["KEYCODE_CAPSLOCK"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "Caps" },
	["KEYCODE_F4"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "F4" },
	["KEYCODE_F2"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "F2" },
	["KEYCODE_LALT"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "Alt" },
	["KEYCODE_F3"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "F3" },
	["KEYCODE_STOP"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", ". >" },
	["KEYCODE_F1"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "F1" },
	["KEYCODE_SLASH"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "/ ?" },
	["KEYCODE_SPACE"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "Space" },
	["KEYCODE_COMMA"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", ", <" },
	["KEYCODE_M"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "M" },
	["KEYCODE_N"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "N" },
	["KEYCODE_ASTERISK"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "KP * (PrtScr)" },
	["KEYCODE_RSHIFT"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_3", "R-Shift" },
	-- :board4:fdc37c93x:at_keyboard:pc_keyboard_4
	["KEYCODE_F7"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "F7" },
	["KEYCODE_F6"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "F6" },
	["KEYCODE_1PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "KP 1 (End)" },
	["KEYCODE_PLUSPAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "KP +" },
	["KEYCODE_4PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "KP 4 (Left)" },
	["KEYCODE_F9"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "F9" },
	["KEYCODE_NUMLOCK"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "NumLock" },
	["KEYCODE_6PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "KP 6 (Right)" },
	["KEYCODE_SCRLOCK"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "ScrLock" },
	["KEYCODE_F8"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "F8" },
	["KEYCODE_7PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "KP 7 (Home)" },
	["KEYCODE_8PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "KP 8 (Up)" },
	["KEYCODE_9PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "KP 9 (PgUp)" },
	["KEYCODE_5PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "KP 5" },
	["KEYCODE_F10"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "F10" },
	["KEYCODE_MINUSPAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_4", "KP -" },
	-- :board4:fdc37c93x:at_keyboard:pc_keyboard_5
	["KEYCODE_BACKSLASH2"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_5", "(84/102)\\" },
	["KEYCODE_DELPAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_5", "KP . (Del)" },
	["KEYCODE_F12"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_5", "(MF2)F12" },
	["KEYCODE_0PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_5", "KP 0 (Ins)" },
	["KEYCODE_3PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_5", "KP 3 (PgDn)" },
	["KEYCODE_2PAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_5", "KP 2 (Down)" },
	["KEYCODE_F11"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_5", "(MF2)F11" },
	-- :board4:fdc37c93x:at_keyboard:pc_keyboard_6
	["KEYCODE_ENTERPAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)KP Enter" },
	["KEYCODE_DOWN"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Cursor Down" },
	["KEYCODE_HOME"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Home" },
	["KEYCODE_PAUSE"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Pause" },
	["KEYCODE_RCONTROL"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Right Control" },
	["KEYCODE_SLASHPAD"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)KP /" },
	["KEYCODE_PRTSCR"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)PRTSCR" },
	["KEYCODE_DEL"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Delete" },
	["KEYCODE_INSERT"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Insert" },
	["KEYCODE_RALT"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)ALTGR" },
	["KEYCODE_UP"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Cursor Up" },
	["KEYCODE_PGDN"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Page Down" },
	["KEYCODE_PGUP"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Page Up" },
	["KEYCODE_LEFT"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Cursor Left" },
	["KEYCODE_END"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)End" },
	["KEYCODE_RIGHT"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_6", "(MF2)Cursor Right" },
	-- :board4:fdc37c93x:at_keyboard:pc_keyboard_7
	["KEYCODE_PRTSCR"] = { ":board4:fdc37c93x:at_keyboard:pc_keyboard_7", "Print Screen" },
	-- :board4:fdc37c93x:pc_kbdc:MOUSEBTN
	["MOUSECODE_1_BUTTON2"] = { ":board4:fdc37c93x:pc_kbdc:MOUSEBTN", "Mouse Button 2" },
	["MOUSECODE_1_BUTTON1"] = { ":board4:fdc37c93x:pc_kbdc:MOUSEBTN", "Mouse Button 1" },
	-- :board4:fdc37c93x:pc_kbdc:MOUSEX
	["MOUSECODE_1_XAXIS"] = { ":board4:fdc37c93x:pc_kbdc:MOUSEX", "Mouse X" },
	-- :board4:fdc37c93x:pc_kbdc:MOUSEY
	["MOUSECODE_1_YAXIS"] = { ":board4:fdc37c93x:pc_kbdc:MOUSEY", "Mouse Y" },
	-- :pci:4:virge:vga:VGA_SENSE
}

