portmap = {
	-- :LOCK
	["KEYCODE_CAPSLOCK"] = { ":LOCK", "SHIFT LOCK" },
	-- :RESTORE
	["KEYCODE_PRTSCR"] = { ":RESTORE", "RESTORE" },
	-- :ROW0
	["KEYCODE_RALT"] = { ":ROW0", "Crsr Down Up" },
	["KEYCODE_RCONTROL"] = { ":ROW0", "Crsr Right Left" },
	["KEYCODE_F3"] = { ":ROW0", "F5" },
	["KEYCODE_F2"] = { ":ROW0", "F3" },
	["KEYCODE_BACKSPACE"] = { ":ROW0", "INST DEL" },
	["KEYCODE_ENTER"] = { ":ROW0", "Return" },
	["KEYCODE_F1"] = { ":ROW0", "F1" },
	["KEYCODE_F4"] = { ":ROW0", "F7" },
	-- :ROW1
	["KEYCODE_3"] = { ":ROW1", "3  #" },
	["KEYCODE_W"] = { ":ROW1", "W" },
	["KEYCODE_E"] = { ":ROW1", "E" },
	["KEYCODE_S"] = { ":ROW1", "S" },
	["KEYCODE_A"] = { ":ROW1", "A" },
	["KEYCODE_4"] = { ":ROW1", "4  $" },
	["KEYCODE_Z"] = { ":ROW1", "Z" },
	["KEYCODE_LSHIFT"] = { ":ROW1", "Shift (Left)" },
	-- :ROW2
	["KEYCODE_X"] = { ":ROW2", "X" },
	["KEYCODE_F"] = { ":ROW2", "F" },
	["KEYCODE_T"] = { ":ROW2", "T" },
	["KEYCODE_C"] = { ":ROW2", "C" },
	["KEYCODE_R"] = { ":ROW2", "R" },
	["KEYCODE_5"] = { ":ROW2", "5  %" },
	["KEYCODE_D"] = { ":ROW2", "D" },
	["KEYCODE_6"] = { ":ROW2", "6  &" },
	-- :ROW3
	["KEYCODE_Y"] = { ":ROW3", "Y" },
	["KEYCODE_H"] = { ":ROW3", "H" },
	["KEYCODE_G"] = { ":ROW3", "G" },
	["KEYCODE_V"] = { ":ROW3", "V" },
	["KEYCODE_U"] = { ":ROW3", "U" },
	["KEYCODE_B"] = { ":ROW3", "B" },
	["KEYCODE_7"] = { ":ROW3", "7  '" },
	["KEYCODE_8"] = { ":ROW3", "8  (" },
	-- :ROW4
	["KEYCODE_J"] = { ":ROW4", "J" },
	["KEYCODE_I"] = { ":ROW4", "I" },
	["KEYCODE_9"] = { ":ROW4", "9  )" },
	["KEYCODE_O"] = { ":ROW4", "O" },
	["KEYCODE_N"] = { ":ROW4", "N" },
	["KEYCODE_M"] = { ":ROW4", "M" },
	["KEYCODE_0"] = { ":ROW4", "0" },
	["KEYCODE_K"] = { ":ROW4", "K" },
	-- :ROW5
	["KEYCODE_STOP"] = { ":ROW5", ".  >" },
	["KEYCODE_COMMA"] = { ":ROW5", ",  <" },
	["KEYCODE_OPENBRACE"] = { ":ROW5", "@" },
	["KEYCODE_P"] = { ":ROW5", "P" },
	["KEYCODE_COLON"] = { ":ROW5", ":  [" },
	["KEYCODE_EQUALS"] = { ":ROW5", "-" },
	["KEYCODE_L"] = { ":ROW5", "L" },
	["KEYCODE_MINUS"] = { ":ROW5", "+" },
	-- :ROW6
	["KEYCODE_CLOSEBRACE"] = { ":ROW6", "*" },
	["KEYCODE_DEL"] = { ":ROW6", "↑  Pi" },
	["KEYCODE_SLASH"] = { ":ROW6", "/  ?" },
	["KEYCODE_BACKSLASH2"] = { ":ROW6", "£" },
	["KEYCODE_INSERT"] = { ":ROW6", "CLR HOME" },
	["KEYCODE_BACKSLASH"] = { ":ROW6", "=" },
	["KEYCODE_QUOTE"] = { ":ROW6", ";  ]" },
	["KEYCODE_RSHIFT"] = { ":ROW6", "Shift (Right)" },
	-- :ROW7
	["KEYCODE_1"] = { ":ROW7", "1  !" },
	["KEYCODE_2"] = { ":ROW7", "2  \"" },
	["KEYCODE_TILDE"] = { ":ROW7", "←" },
	["KEYCODE_HOME"] = { ":ROW7", "RUN STOP" },
	["KEYCODE_Q"] = { ":ROW7", "Q" },
	["KEYCODE_LALT"] = { ":ROW7", "CBM" },
	["KEYCODE_TAB"] = { ":ROW7", "Ctrl" },
	["KEYCODE_SPACE"] = { ":ROW7", "Space" },
	-- :iec8:c1541:ADDRESS
	-- :joy2:joy:JOY
	["KEYCODE_LEFT"] = { ":joy2:joy:JOY", "P1 Left" },
	["JOYCODE_1_XAXIS_LEFT_SWITCH"] = { ":joy2:joy:JOY", "P1 Left" },
	["JOYCODE_1_HAT1LEFT"] = { ":joy2:joy:JOY", "P1 Left" },
	["KEYCODE_RIGHT"] = { ":joy2:joy:JOY", "P1 Right" },
	["JOYCODE_1_XAXIS_RIGHT_SWITCH"] = { ":joy2:joy:JOY", "P1 Right" },
	["JOYCODE_1_HAT1RIGHT"] = { ":joy2:joy:JOY", "P1 Right" },
	["KEYCODE_DOWN"] = { ":joy2:joy:JOY", "P1 Down" },
	["JOYCODE_1_YAXIS_DOWN_SWITCH"] = { ":joy2:joy:JOY", "P1 Down" },
	["JOYCODE_1_HAT1DOWN"] = { ":joy2:joy:JOY", "P1 Down" },
	["KEYCODE_LCONTROL"] = { ":joy2:joy:JOY", "P1 Button 1" },
	["MOUSECODE_1_BUTTON1"] = { ":joy2:joy:JOY", "P1 Button 1" },
	["GUNCODE_1_BUTTON1"] = { ":joy2:joy:JOY", "P1 Button 1" },
	["JOYCODE_1_BUTTON1"] = { ":joy2:joy:JOY", "P1 Button 1" },
	["KEYCODE_UP"] = { ":joy2:joy:JOY", "P1 Up" },
	["JOYCODE_1_YAXIS_UP_SWITCH"] = { ":joy2:joy:JOY", "P1 Up" },
	["JOYCODE_1_HAT1UP"] = { ":joy2:joy:JOY", "P1 Up" },
}

