portmap = {
	-- :cheetah
	["KEYCODE_DOWN"] = { ":cheetah", "Cheetah 125 Down" },
	["JOYCODE_1_YAXIS_DOWN_SWITCH"] = { ":cheetah", "Cheetah 125 Down" },
	["JOYCODE_1_HAT1DOWN"] = { ":cheetah", "Cheetah 125 Down" },
	["KEYCODE_LALT"] = { ":cheetah", "Cheetah 125 Rotate Left" },
	["MOUSECODE_1_BUTTON3"] = { ":cheetah", "Cheetah 125 Rotate Left" },
	["GUNCODE_1_BUTTON2"] = { ":cheetah", "Cheetah 125 Rotate Left" },
	["JOYCODE_1_BUTTON2"] = { ":cheetah", "Cheetah 125 Rotate Left" },
	["KEYCODE_UP"] = { ":cheetah", "Cheetah 125 Up" },
	["JOYCODE_1_YAXIS_UP_SWITCH"] = { ":cheetah", "Cheetah 125 Up" },
	["JOYCODE_1_HAT1UP"] = { ":cheetah", "Cheetah 125 Up" },
	["KEYCODE_RIGHT"] = { ":cheetah", "Cheetah 125 Right" },
	["JOYCODE_1_XAXIS_RIGHT_SWITCH"] = { ":cheetah", "Cheetah 125 Right" },
	["JOYCODE_1_HAT1RIGHT"] = { ":cheetah", "Cheetah 125 Right" },
	["KEYCODE_SPACE"] = { ":cheetah", "Cheetah 125 Rotate Right" },
	["MOUSECODE_1_BUTTON2"] = { ":cheetah", "Cheetah 125 Rotate Right" },
	["JOYCODE_1_BUTTON3"] = { ":cheetah", "Cheetah 125 Rotate Right" },
	["KEYCODE_LEFT"] = { ":cheetah", "Cheetah 125 Left" },
	["JOYCODE_1_XAXIS_LEFT_SWITCH"] = { ":cheetah", "Cheetah 125 Left" },
	["JOYCODE_1_HAT1LEFT"] = { ":cheetah", "Cheetah 125 Left" },
	["KEYCODE_LCONTROL"] = { ":cheetah", "Cheetah 125 Fire" },
	["MOUSECODE_1_BUTTON1"] = { ":cheetah", "Cheetah 125 Fire" },
	["GUNCODE_1_BUTTON1"] = { ":cheetah", "Cheetah 125 Fire" },
	["JOYCODE_1_BUTTON1"] = { ":cheetah", "Cheetah 125 Fire" },
	-- :controller_type
	-- :green_display
	-- :kbrow.0
	["KEYCODE_9PAD"] = { ":kbrow.0", "Keypad 9" },
	["KEYCODE_6PAD"] = { ":kbrow.0", "Keypad 6" },
	["KEYCODE_DELPAD"] = { ":kbrow.0", "Keypad ." },
	["KEYCODE_UP"] = { ":kbrow.0", "↑" },
	["KEYCODE_DOWN"] = { ":kbrow.0", "↓" },
	["KEYCODE_RIGHT"] = { ":kbrow.0", "→" },
	["KEYCODE_ENTERPAD"] = { ":kbrow.0", "Keypad Enter" },
	["KEYCODE_3PAD"] = { ":kbrow.0", "Keypad 3" },
	-- :kbrow.1
	["KEYCODE_7PAD"] = { ":kbrow.1", "Keypad 7" },
	["KEYCODE_5PAD"] = { ":kbrow.1", "Keypad 5" },
	["KEYCODE_LEFT"] = { ":kbrow.1", "←" },
	["KEYCODE_0PAD"] = { ":kbrow.1", "Keypad 0" },
	["KEYCODE_2PAD"] = { ":kbrow.1", "Keypad 2" },
	["KEYCODE_END"] = { ":kbrow.1", "Copy" },
	["KEYCODE_1PAD"] = { ":kbrow.1", "Keypad 1" },
	["KEYCODE_8PAD"] = { ":kbrow.1", "Keypad 8" },
	-- :kbrow.2
	["KEYCODE_CLOSEBRACE"] = { ":kbrow.2", "[" },
	["KEYCODE_4PAD"] = { ":kbrow.2", "Keypad 4" },
	["KEYCODE_BACKSLASH"] = { ":kbrow.2", "]" },
	["KEYCODE_RCONTROL"] = { ":kbrow.2", "\" },
	["KEYCODE_RALT"] = { ":kbrow.2", "Ctrl" },
	["KEYCODE_LSHIFT"] = { ":kbrow.2", "Shift" },
	["KEYCODE_RSHIFT"] = { ":kbrow.2", "Shift" },
	["KEYCODE_BACKSPACE"] = { ":kbrow.2", "Clr" },
	["KEYCODE_ENTER"] = { ":kbrow.2", "Enter" },
	-- :kbrow.3
	["KEYCODE_MINUS"] = { ":kbrow.3", "-  =" },
	["KEYCODE_SLASH"] = { ":kbrow.3", "/  ?" },
	["KEYCODE_OPENBRACE"] = { ":kbrow.3", "@  ¦" },
	["KEYCODE_P"] = { ":kbrow.3", "p  P" },
	["KEYCODE_STOP"] = { ":kbrow.3", ".  >" },
	["KEYCODE_COLON"] = { ":kbrow.3", ":  *" },
	["KEYCODE_EQUALS"] = { ":kbrow.3", "↑ £" },
	["KEYCODE_QUOTE"] = { ":kbrow.3", ";  +" },
	-- :kbrow.4
	["KEYCODE_0"] = { ":kbrow.4", "0  _" },
	["KEYCODE_O"] = { ":kbrow.4", "o  O" },
	["KEYCODE_L"] = { ":kbrow.4", "l  L" },
	["KEYCODE_COMMA"] = { ":kbrow.4", ",  <" },
	["KEYCODE_K"] = { ":kbrow.4", "k  K" },
	["KEYCODE_M"] = { ":kbrow.4", "m  M" },
	["KEYCODE_I"] = { ":kbrow.4", "i  I" },
	["KEYCODE_9"] = { ":kbrow.4", "9  )" },
	-- :kbrow.5
	["KEYCODE_Y"] = { ":kbrow.5", "y  Y" },
	["KEYCODE_U"] = { ":kbrow.5", "u  U" },
	["KEYCODE_7"] = { ":kbrow.5", "7  '" },
	["KEYCODE_H"] = { ":kbrow.5", "h  H" },
	["KEYCODE_8"] = { ":kbrow.5", "8  (" },
	["KEYCODE_SPACE"] = { ":kbrow.5", "Space" },
	["KEYCODE_N"] = { ":kbrow.5", "n  N" },
	["KEYCODE_J"] = { ":kbrow.5", "j  J" },
	-- :kbrow.6
	["KEYCODE_6"] = { ":kbrow.6", "6  &" },
	["KEYCODE_R"] = { ":kbrow.6", "r  R" },
	["KEYCODE_V"] = { ":kbrow.6", "v  V" },
	["KEYCODE_5"] = { ":kbrow.6", "5  %" },
	["KEYCODE_G"] = { ":kbrow.6", "g  G" },
	["KEYCODE_T"] = { ":kbrow.6", "t  T" },
	["KEYCODE_B"] = { ":kbrow.6", "b  B" },
	["KEYCODE_F"] = { ":kbrow.6", "f  F" },
	-- :kbrow.7
	["KEYCODE_C"] = { ":kbrow.7", "c  C" },
	["KEYCODE_E"] = { ":kbrow.7", "e  E" },
	["KEYCODE_W"] = { ":kbrow.7", "w  W" },
	["KEYCODE_D"] = { ":kbrow.7", "d  D" },
	["KEYCODE_S"] = { ":kbrow.7", "s  S" },
	["KEYCODE_X"] = { ":kbrow.7", "x  X" },
	["KEYCODE_4"] = { ":kbrow.7", "4  $" },
	["KEYCODE_3"] = { ":kbrow.7", "3  #" },
	-- :kbrow.8
	["KEYCODE_TILDE"] = { ":kbrow.8", "Esc" },
	["KEYCODE_Z"] = { ":kbrow.8", "z  Z" },
	["KEYCODE_Q"] = { ":kbrow.8", "q  Q" },
	["KEYCODE_A"] = { ":kbrow.8", "a  A" },
	["KEYCODE_2"] = { ":kbrow.8", "2  "  ~" },
	["KEYCODE_TAB"] = { ":kbrow.8", "Tab" },
	["KEYCODE_CAPSLOCK"] = { ":kbrow.8", "Caps Lock" },
	["KEYCODE_1"] = { ":kbrow.8", "1  !" },
	-- :kbrow.9
	["KEYCODE_LEFT"] = { ":kbrow.9", "P1 Left" },
	["JOYCODE_1_XAXIS_LEFT_SWITCH"] = { ":kbrow.9", "P1 Left" },
	["JOYCODE_1_HAT1LEFT"] = { ":kbrow.9", "P1 Left" },
	["KEYCODE_INSERT"] = { ":kbrow.9", "Del" },
	["KEYCODE_UP"] = { ":kbrow.9", "P1 Up" },
	["JOYCODE_1_YAXIS_UP_SWITCH"] = { ":kbrow.9", "P1 Up" },
	["JOYCODE_1_HAT1UP"] = { ":kbrow.9", "P1 Up" },
	["KEYCODE_DOWN"] = { ":kbrow.9", "P1 Down" },
	["JOYCODE_1_YAXIS_DOWN_SWITCH"] = { ":kbrow.9", "P1 Down" },
	["JOYCODE_1_HAT1DOWN"] = { ":kbrow.9", "P1 Down" },
	["KEYCODE_RIGHT"] = { ":kbrow.9", "P1 Right" },
	["JOYCODE_1_XAXIS_RIGHT_SWITCH"] = { ":kbrow.9", "P1 Right" },
	["JOYCODE_1_HAT1RIGHT"] = { ":kbrow.9", "P1 Right" },
	["KEYCODE_LCONTROL"] = { ":kbrow.9", "P1 Button 1" },
	["MOUSECODE_1_BUTTON1"] = { ":kbrow.9", "P1 Button 1" },
	["GUNCODE_1_BUTTON1"] = { ":kbrow.9", "P1 Button 1" },
	["JOYCODE_1_BUTTON1"] = { ":kbrow.9", "P1 Button 1" },
	["KEYCODE_LALT"] = { ":kbrow.9", "P1 Button 2" },
	["MOUSECODE_1_BUTTON3"] = { ":kbrow.9", "P1 Button 2" },
	["GUNCODE_1_BUTTON2"] = { ":kbrow.9", "P1 Button 2" },
	["JOYCODE_1_BUTTON2"] = { ":kbrow.9", "P1 Button 2" },
	-- :mouse_input1
	["MOUSECODE_1_XAXIS"] = { ":mouse_input1", "Mouse X" },
	-- :mouse_input2
	["MOUSECODE_1_YAXIS"] = { ":mouse_input2", "Mouse Y" },
	-- :mouse_input3
	["MOUSECODE_1_BUTTON3"] = { ":mouse_input3", "Middle mouse button" },
	["MOUSECODE_1_BUTTON1"] = { ":mouse_input3", "Left mouse button" },
	["MOUSECODE_1_BUTTON2"] = { ":mouse_input3", "Right mouse button" },
	-- :solder_links
}

