portmap = {
	-- :board2:comat:serport0:logitech_mouse:BTN
	["MOUSECODE_1_BUTTON2"] = { ":board2:comat:serport0:logitech_mouse:BTN", "P1 Button 3" },
	["MOUSECODE_1_BUTTON1"] = { ":board2:comat:serport0:logitech_mouse:BTN", "P1 Button 1" },
	["MOUSECODE_1_BUTTON3"] = { ":board2:comat:serport0:logitech_mouse:BTN", "P1 Button 2" },
	-- :board2:comat:serport0:logitech_mouse:X
	["MOUSECODE_1_XAXIS"] = { ":board2:comat:serport0:logitech_mouse:X", "Mouse X" },
	-- :board2:comat:serport0:logitech_mouse:Y
	["MOUSECODE_1_YAXIS"] = { ":board2:comat:serport0:logitech_mouse:Y", "Mouse Y" },
	-- :board3:ide:DSW
	-- :board4:lpt:DSW
	-- :isa1:svga_et4kw32i:vga:VGA_SENSE
	-- :kbd:ms_naturl:P1.0
	["KEYCODE_ENTERPAD"] = { ":kbd:ms_naturl:P1.0", "Keyboard" },
	["KEYCODE_LWIN"] = { ":kbd:ms_naturl:P1.0", "Left Win" },
	["KEYCODE_ENTERPAD"] = { ":kbd:ms_naturl:P1.0", "Keypad Enter" },
	["KEYCODE_SCRLOCK"] = { ":kbd:ms_naturl:P1.0", "Scroll Lock" },
	-- :kbd:ms_naturl:P1.1
	["KEYCODE_CAPSLOCK"] = { ":kbd:ms_naturl:P1.1", "Keyboard" },
	["KEYCODE_CAPSLOCK"] = { ":kbd:ms_naturl:P1.1", "Caps Lock" },
	["KEYCODE_LCONTROL"] = { ":kbd:ms_naturl:P1.1", "Left Ctrl" },
	["KEYCODE_RCONTROL"] = { ":kbd:ms_naturl:P1.1", "Right Ctrl" },
	-- :kbd:ms_naturl:P1.2
	["KEYCODE_F2"] = { ":kbd:ms_naturl:P1.2", "Keyboard" },
	["KEYCODE_PGDN"] = { ":kbd:ms_naturl:P1.2", "Page Down" },
	["KEYCODE_X"] = { ":kbd:ms_naturl:P1.2", "X" },
	["KEYCODE_F2"] = { ":kbd:ms_naturl:P1.2", "F2" },
	["KEYCODE_F1"] = { ":kbd:ms_naturl:P1.2", "F1" },
	["KEYCODE_W"] = { ":kbd:ms_naturl:P1.2", "W" },
	["KEYCODE_PGUP"] = { ":kbd:ms_naturl:P1.2", "Page Up" },
	["KEYCODE_2"] = { ":kbd:ms_naturl:P1.2", "2" },
	["KEYCODE_S"] = { ":kbd:ms_naturl:P1.2", "S" },
	-- :kbd:ms_naturl:P1.3
	["KEYCODE_MINUSPAD"] = { ":kbd:ms_naturl:P1.3", "Keypad -" },
	["KEYCODE_NUMLOCK"] = { ":kbd:ms_naturl:P1.3", "Num Lock" },
	["KEYCODE_RALT"] = { ":kbd:ms_naturl:P1.3", "Right Alt" },
	["KEYCODE_NUMLOCK"] = { ":kbd:ms_naturl:P1.3", "Keyboard" },
	["KEYCODE_LALT"] = { ":kbd:ms_naturl:P1.3", "Left Alt" },
	-- :kbd:ms_naturl:P1.4
	["KEYCODE_D"] = { ":kbd:ms_naturl:P1.4", "D" },
	["KEYCODE_E"] = { ":kbd:ms_naturl:P1.4", "E" },
	["KEYCODE_8"] = { ":kbd:ms_naturl:P1.4", "Keyboard" },
	["KEYCODE_8"] = { ":kbd:ms_naturl:P1.4", "8" },
	["KEYCODE_I"] = { ":kbd:ms_naturl:P1.4", "I" },
	["KEYCODE_K"] = { ":kbd:ms_naturl:P1.4", "K" },
	["KEYCODE_COMMA"] = { ":kbd:ms_naturl:P1.4", "," },
	["KEYCODE_C"] = { ":kbd:ms_naturl:P1.4", "C" },
	["KEYCODE_3"] = { ":kbd:ms_naturl:P1.4", "3" },
	-- :kbd:ms_naturl:P1.5
	["KEYCODE_T"] = { ":kbd:ms_naturl:P1.5", "T" },
	["KEYCODE_5"] = { ":kbd:ms_naturl:P1.5", "5" },
	["KEYCODE_V"] = { ":kbd:ms_naturl:P1.5", "V" },
	["KEYCODE_G"] = { ":kbd:ms_naturl:P1.5", "G" },
	["KEYCODE_5"] = { ":kbd:ms_naturl:P1.5", "Keyboard" },
	["KEYCODE_F"] = { ":kbd:ms_naturl:P1.5", "F" },
	["KEYCODE_R"] = { ":kbd:ms_naturl:P1.5", "R" },
	["KEYCODE_B"] = { ":kbd:ms_naturl:P1.5", "B" },
	["KEYCODE_4"] = { ":kbd:ms_naturl:P1.5", "4" },
	-- :kbd:ms_naturl:P1.6
	["KEYCODE_TILDE"] = { ":kbd:ms_naturl:P1.6", "Keyboard" },
	["KEYCODE_ESC"] = { ":kbd:ms_naturl:P1.6", "Esc" },
	["KEYCODE_TAB"] = { ":kbd:ms_naturl:P1.6", "Tab" },
	["KEYCODE_Q"] = { ":kbd:ms_naturl:P1.6", "Q" },
	["KEYCODE_TILDE"] = { ":kbd:ms_naturl:P1.6", "`" },
	["KEYCODE_1"] = { ":kbd:ms_naturl:P1.6", "1" },
	["KEYCODE_Z"] = { ":kbd:ms_naturl:P1.6", "Z" },
	["KEYCODE_A"] = { ":kbd:ms_naturl:P1.6", "A" },
	-- :kbd:ms_naturl:P1.7
	["KEYCODE_LSHIFT"] = { ":kbd:ms_naturl:P1.7", "Left Shift" },
	["KEYCODE_CANCEL"] = { ":kbd:ms_naturl:P1.7", "Break" },
	["KEYCODE_CANCEL"] = { ":kbd:ms_naturl:P1.7", "Keyboard" },
	["KEYCODE_RSHIFT"] = { ":kbd:ms_naturl:P1.7", "Right Shift" },
	-- :kbd:ms_naturl:P2.0
	["KEYCODE_U"] = { ":kbd:ms_naturl:P2.0", "U" },
	["KEYCODE_6"] = { ":kbd:ms_naturl:P2.0", "6" },
	["KEYCODE_7"] = { ":kbd:ms_naturl:P2.0", "7" },
	["KEYCODE_H"] = { ":kbd:ms_naturl:P2.0", "H" },
	["KEYCODE_Y"] = { ":kbd:ms_naturl:P2.0", "Y" },
	["KEYCODE_J"] = { ":kbd:ms_naturl:P2.0", "J" },
	["KEYCODE_M"] = { ":kbd:ms_naturl:P2.0", "M" },
	["KEYCODE_N"] = { ":kbd:ms_naturl:P2.0", "N" },
	["KEYCODE_7"] = { ":kbd:ms_naturl:P2.0", "Keyboard" },
	-- :kbd:ms_naturl:P2.1
	["KEYCODE_F6"] = { ":kbd:ms_naturl:P2.1", "Keyboard" },
	["KEYCODE_LEFT"] = { ":kbd:ms_naturl:P2.1", "Cursor Left" },
	["KEYCODE_ENTER"] = { ":kbd:ms_naturl:P2.1", "Enter" },
	["KEYCODE_BACKSLASH"] = { ":kbd:ms_naturl:P2.1", "\\" },
	["KEYCODE_CLOSEBRACE"] = { ":kbd:ms_naturl:P2.1", "]" },
	["KEYCODE_BACKSPACE"] = { ":kbd:ms_naturl:P2.1", "Backspace" },
	["KEYCODE_F5"] = { ":kbd:ms_naturl:P2.1", "F5" },
	["KEYCODE_EQUALS"] = { ":kbd:ms_naturl:P2.1", "=" },
	["KEYCODE_F6"] = { ":kbd:ms_naturl:P2.1", "F6" },
	-- :kbd:ms_naturl:P2.2
	["KEYCODE_F8"] = { ":kbd:ms_naturl:P2.2", "Keyboard" },
	["KEYCODE_9"] = { ":kbd:ms_naturl:P2.2", "9" },
	["KEYCODE_OPENBRACE"] = { ":kbd:ms_naturl:P2.2", "[" },
	["KEYCODE_L"] = { ":kbd:ms_naturl:P2.2", "L" },
	["KEYCODE_MINUS"] = { ":kbd:ms_naturl:P2.2", "-" },
	["KEYCODE_STOP"] = { ":kbd:ms_naturl:P2.2", "." },
	["KEYCODE_O"] = { ":kbd:ms_naturl:P2.2", "O" },
	["KEYCODE_F7"] = { ":kbd:ms_naturl:P2.2", "F7" },
	["KEYCODE_F8"] = { ":kbd:ms_naturl:P2.2", "F8" },
	-- :kbd:ms_naturl:P2.3
	["KEYCODE_F10"] = { ":kbd:ms_naturl:P2.3", "F10" },
	["KEYCODE_F10"] = { ":kbd:ms_naturl:P2.3", "Keyboard" },
	["KEYCODE_QUOTE"] = { ":kbd:ms_naturl:P2.3", "'" },
	["KEYCODE_DOWN"] = { ":kbd:ms_naturl:P2.3", "Cursor Down" },
	["KEYCODE_F9"] = { ":kbd:ms_naturl:P2.3", "F9" },
	["KEYCODE_SLASH"] = { ":kbd:ms_naturl:P2.3", "/" },
	["KEYCODE_P"] = { ":kbd:ms_naturl:P2.3", "P" },
	["KEYCODE_COLON"] = { ":kbd:ms_naturl:P2.3", ";" },
	["KEYCODE_0"] = { ":kbd:ms_naturl:P2.3", "0" },
	-- :kbd:ms_naturl:P2.4
	["KEYCODE_SPACE"] = { ":kbd:ms_naturl:P2.4", "Space" },
	["KEYCODE_UP"] = { ":kbd:ms_naturl:P2.4", "Cursor Up" },
	["KEYCODE_SPACE"] = { ":kbd:ms_naturl:P2.4", "Keyboard" },
	["KEYCODE_RIGHT"] = { ":kbd:ms_naturl:P2.4", "Cursor Right" },
	["KEYCODE_RWIN"] = { ":kbd:ms_naturl:P2.4", "Right Win" },
	-- :kbd:ms_naturl:P2.5
	["KEYCODE_F12"] = { ":kbd:ms_naturl:P2.5", "Keyboard" },
	["KEYCODE_F12"] = { ":kbd:ms_naturl:P2.5", "F12" },
	["KEYCODE_8PAD"] = { ":kbd:ms_naturl:P2.5", "Keypad 8" },
	["KEYCODE_2PAD"] = { ":kbd:ms_naturl:P2.5", "Keypad 2" },
	["KEYCODE_5PAD"] = { ":kbd:ms_naturl:P2.5", "Keypad 5" },
	["KEYCODE_END"] = { ":kbd:ms_naturl:P2.5", "End" },
	["KEYCODE_0PAD"] = { ":kbd:ms_naturl:P2.5", "Keypad 0" },
	["KEYCODE_F11"] = { ":kbd:ms_naturl:P2.5", "F11" },
	["KEYCODE_HOME"] = { ":kbd:ms_naturl:P2.5", "Home" },
	-- :kbd:ms_naturl:P2.6
	["KEYCODE_F4"] = { ":kbd:ms_naturl:P2.6", "Keyboard" },
	["KEYCODE_DEL"] = { ":kbd:ms_naturl:P2.6", "Delete" },
	["KEYCODE_INSERT"] = { ":kbd:ms_naturl:P2.6", "Insert" },
	["KEYCODE_DELPAD"] = { ":kbd:ms_naturl:P2.6", "Keypad ." },
	["KEYCODE_3PAD"] = { ":kbd:ms_naturl:P2.6", "Keypad 3" },
	["KEYCODE_F3"] = { ":kbd:ms_naturl:P2.6", "F3" },
	["KEYCODE_F4"] = { ":kbd:ms_naturl:P2.6", "F4" },
	["KEYCODE_9PAD"] = { ":kbd:ms_naturl:P2.6", "Keypad 9" },
	["KEYCODE_6PAD"] = { ":kbd:ms_naturl:P2.6", "Keypad 6" },
	-- :kbd:ms_naturl:P2.7
	["KEYCODE_SLASHPAD"] = { ":kbd:ms_naturl:P2.7", "Keypad /" },
	["KEYCODE_MENU"] = { ":kbd:ms_naturl:P2.7", "Keyboard" },
	["KEYCODE_4PAD"] = { ":kbd:ms_naturl:P2.7", "Keypad 4" },
	["KEYCODE_ASTERISK"] = { ":kbd:ms_naturl:P2.7", "Keypad *" },
	["KEYCODE_7PAD"] = { ":kbd:ms_naturl:P2.7", "Keypad 7" },
	["KEYCODE_1PAD"] = { ":kbd:ms_naturl:P2.7", "Keypad 1" },
	["KEYCODE_MENU"] = { ":kbd:ms_naturl:P2.7", "Menu" },
	["KEYCODE_PRTSCR"] = { ":kbd:ms_naturl:P2.7", "Print Screen" },
	["KEYCODE_PLUSPAD"] = { ":kbd:ms_naturl:P2.7", "Keypad +" },
	-- :keybc:P1
}
