portmap = {
	-- :joy1:townspad:PAD
	["KEYCODE_1"] = { ":joy1:townspad:PAD", "%p Run" },
	["JOYCODE_1_START"] = { ":joy1:townspad:PAD", "%p Run" },
	["KEYCODE_LEFT"] = { ":joy1:townspad:PAD", "P1 Left" },
	["JOYCODE_1_XAXIS_LEFT_SWITCH"] = { ":joy1:townspad:PAD", "P1 Left" },
	["JOYCODE_1_HAT1LEFT"] = { ":joy1:townspad:PAD", "P1 Left" },
	["KEYCODE_UP"] = { ":joy1:townspad:PAD", "P1 Up" },
	["JOYCODE_1_YAXIS_UP_SWITCH"] = { ":joy1:townspad:PAD", "P1 Up" },
	["JOYCODE_1_HAT1UP"] = { ":joy1:townspad:PAD", "P1 Up" },
	["KEYCODE_LALT"] = { ":joy1:townspad:PAD", "P1 B" },
	["MOUSECODE_1_BUTTON3"] = { ":joy1:townspad:PAD", "P1 B" },
	["GUNCODE_1_BUTTON2"] = { ":joy1:townspad:PAD", "P1 B" },
	["JOYCODE_1_BUTTON2"] = { ":joy1:townspad:PAD", "P1 B" },
	["KEYCODE_DOWN"] = { ":joy1:townspad:PAD", "P1 Down" },
	["JOYCODE_1_YAXIS_DOWN_SWITCH"] = { ":joy1:townspad:PAD", "P1 Down" },
	["JOYCODE_1_HAT1DOWN"] = { ":joy1:townspad:PAD", "P1 Down" },
	["KEYCODE_LCONTROL"] = { ":joy1:townspad:PAD", "%p A" },
	["MOUSECODE_1_BUTTON1"] = { ":joy1:townspad:PAD", "%p A" },
	["GUNCODE_1_BUTTON1"] = { ":joy1:townspad:PAD", "%p A" },
	["JOYCODE_1_BUTTON1"] = { ":joy1:townspad:PAD", "%p A" },
	["KEYCODE_LALT"] = { ":joy1:townspad:PAD", "%p B" },
	["MOUSECODE_1_BUTTON3"] = { ":joy1:townspad:PAD", "%p B" },
	["GUNCODE_1_BUTTON2"] = { ":joy1:townspad:PAD", "%p B" },
	["JOYCODE_1_BUTTON2"] = { ":joy1:townspad:PAD", "%p B" },
	["KEYCODE_1"] = { ":joy1:townspad:PAD", "P1 Run" },
	["JOYCODE_1_START"] = { ":joy1:townspad:PAD", "P1 Run" },
	["KEYCODE_RIGHT"] = { ":joy1:townspad:PAD", "P1 Right" },
	["JOYCODE_1_XAXIS_RIGHT_SWITCH"] = { ":joy1:townspad:PAD", "P1 Right" },
	["JOYCODE_1_HAT1RIGHT"] = { ":joy1:townspad:PAD", "P1 Right" },
	["KEYCODE_LCONTROL"] = { ":joy1:townspad:PAD", "P1 A" },
	["MOUSECODE_1_BUTTON1"] = { ":joy1:townspad:PAD", "P1 A" },
	["GUNCODE_1_BUTTON1"] = { ":joy1:townspad:PAD", "P1 A" },
	["JOYCODE_1_BUTTON1"] = { ":joy1:townspad:PAD", "P1 A" },
	["KEYCODE_5"] = { ":joy1:townspad:PAD", "P1 Select" },
	["JOYCODE_1_SELECT"] = { ":joy1:townspad:PAD", "P1 Select" },
	-- :joy2:townspad:PAD
	["KEYCODE_2"] = { ":joy2:townspad:PAD", "%p Run" },
	["KEYCODE_S"] = { ":joy2:townspad:PAD", "P2 B" },
	["MOUSECODE_2_UNKNOWN_SWITCH"] = { ":joy2:townspad:PAD", "P2 B" },
	["GUNCODE_2_UNKNOWN_SWITCH"] = { ":joy2:townspad:PAD", "P2 B" },
	["KEYCODE_A"] = { ":joy2:townspad:PAD", "%p A" },
	["MOUSECODE_2_UNKNOWN_SWITCH"] = { ":joy2:townspad:PAD", "%p A" },
	["GUNCODE_2_UNKNOWN_SWITCH"] = { ":joy2:townspad:PAD", "%p A" },
	["KEYCODE_D"] = { ":joy2:townspad:PAD", "P2 Left" },
	["KEYCODE_R"] = { ":joy2:townspad:PAD", "P2 Up" },
	["KEYCODE_A"] = { ":joy2:townspad:PAD", "P2 A" },
	["MOUSECODE_2_UNKNOWN_SWITCH"] = { ":joy2:townspad:PAD", "P2 A" },
	["GUNCODE_2_UNKNOWN_SWITCH"] = { ":joy2:townspad:PAD", "P2 A" },
	["KEYCODE_6"] = { ":joy2:townspad:PAD", "P2 Select" },
	["KEYCODE_F"] = { ":joy2:townspad:PAD", "P2 Down" },
	["KEYCODE_S"] = { ":joy2:townspad:PAD", "%p B" },
	["MOUSECODE_2_UNKNOWN_SWITCH"] = { ":joy2:townspad:PAD", "%p B" },
	["GUNCODE_2_UNKNOWN_SWITCH"] = { ":joy2:townspad:PAD", "%p B" },
	["KEYCODE_G"] = { ":joy2:townspad:PAD", "P2 Right" },
	["KEYCODE_2"] = { ":joy2:townspad:PAD", "P2 Run" },
	-- :keyboard:x68k:LINE0
	["KEYCODE_1"] = { ":keyboard:x68k:LINE0", "1  !  ぬ" },
	["KEYCODE_2"] = { ":keyboard:x68k:LINE0", "2  "  ふ" },
	["KEYCODE_4"] = { ":keyboard:x68k:LINE0", "4  $  う  ぅ" },
	["KEYCODE_ESC"] = { ":keyboard:x68k:LINE0", "ESC" },
	["KEYCODE_5"] = { ":keyboard:x68k:LINE0", "5  %  え  ぇ" },
	["KEYCODE_6"] = { ":keyboard:x68k:LINE0", "6  &  お  ぉ" },
	["KEYCODE_3"] = { ":keyboard:x68k:LINE0", "3  #  あ  ぁ" },
	-- :keyboard:x68k:LINE1
	["KEYCODE_BACKSPACE"] = { ":keyboard:x68k:LINE1", "BS" },
	["KEYCODE_8"] = { ":keyboard:x68k:LINE1", "8  (  ゆ  ゅ" },
	["KEYCODE_0"] = { ":keyboard:x68k:LINE1", "0  わ  を" },
	["KEYCODE_EQUALS"] = { ":keyboard:x68k:LINE1", "^  へ" },
	["KEYCODE_7"] = { ":keyboard:x68k:LINE1", "7  '  や  ゃ" },
	["KEYCODE_MINUS"] = { ":keyboard:x68k:LINE1", "-  =  ほ" },
	["KEYCODE_9"] = { ":keyboard:x68k:LINE1", "9  )  よ  ょ" },
	["KEYCODE_TILDE"] = { ":keyboard:x68k:LINE1", "¥  |  ー" },
	-- :keyboard:x68k:LINE2
	["KEYCODE_E"] = { ":keyboard:x68k:LINE2", "E  い  ぃ" },
	["KEYCODE_U"] = { ":keyboard:x68k:LINE2", "U  な" },
	["KEYCODE_Y"] = { ":keyboard:x68k:LINE2", "Y  ん" },
	["KEYCODE_T"] = { ":keyboard:x68k:LINE2", "T  か" },
	["KEYCODE_TAB"] = { ":keyboard:x68k:LINE2", "TAB" },
	["KEYCODE_Q"] = { ":keyboard:x68k:LINE2", "Q  た" },
	["KEYCODE_R"] = { ":keyboard:x68k:LINE2", "R  す" },
	["KEYCODE_W"] = { ":keyboard:x68k:LINE2", "W  て" },
	-- :keyboard:x68k:LINE3
	["KEYCODE_OPENBRACE"] = { ":keyboard:x68k:LINE3", "@  `  ゛" },
	["KEYCODE_CLOSEBRACE"] = { ":keyboard:x68k:LINE3", "[  {  ゜ 「" },
	["KEYCODE_S"] = { ":keyboard:x68k:LINE3", "S  と" },
	["KEYCODE_I"] = { ":keyboard:x68k:LINE3", "I  に" },
	["KEYCODE_A"] = { ":keyboard:x68k:LINE3", "A  ち" },
	["KEYCODE_O"] = { ":keyboard:x68k:LINE3", "O  ら" },
	["KEYCODE_P"] = { ":keyboard:x68k:LINE3", "P  せ" },
	["KEYCODE_ENTER"] = { ":keyboard:x68k:LINE3", "Enter" },
	-- :keyboard:x68k:LINE4
	["KEYCODE_D"] = { ":keyboard:x68k:LINE4", "D  し" },
	["KEYCODE_K"] = { ":keyboard:x68k:LINE4", "K  の" },
	["KEYCODE_L"] = { ":keyboard:x68k:LINE4", "L  り" },
	["KEYCODE_COLON"] = { ":keyboard:x68k:LINE4", ";  +  れ" },
	["KEYCODE_F"] = { ":keyboard:x68k:LINE4", "F  は" },
	["KEYCODE_J"] = { ":keyboard:x68k:LINE4", "J  ま" },
	["KEYCODE_G"] = { ":keyboard:x68k:LINE4", "G  き" },
	["KEYCODE_H"] = { ":keyboard:x68k:LINE4", "H  く" },
	-- :keyboard:x68k:LINE5
	["KEYCODE_N"] = { ":keyboard:x68k:LINE5", "N  み" },
	["KEYCODE_C"] = { ":keyboard:x68k:LINE5", "C  そ" },
	["KEYCODE_B"] = { ":keyboard:x68k:LINE5", "B  こ" },
	["KEYCODE_V"] = { ":keyboard:x68k:LINE5", "V  ひ" },
	["KEYCODE_X"] = { ":keyboard:x68k:LINE5", "X  さ" },
	["KEYCODE_BACKSLASH"] = { ":keyboard:x68k:LINE5", "]  }  む  」" },
	["KEYCODE_Z"] = { ":keyboard:x68k:LINE5", "Z  つ  っ" },
	["KEYCODE_QUOTE"] = { ":keyboard:x68k:LINE5", ":  *  け" },
	-- :keyboard:x68k:LINE6
	["KEYCODE_SPACE"] = { ":keyboard:x68k:LINE6", "Space" },
	["KEYCODE_STOP"] = { ":keyboard:x68k:LINE6", ".  >  る  。" },
	["KEYCODE_COMMA"] = { ":keyboard:x68k:LINE6", ",  <  ね  、" },
	["KEYCODE_HOME"] = { ":keyboard:x68k:LINE6", "HOME" },
	["KEYCODE_SLASH"] = { ":keyboard:x68k:LINE6", "/  ?  め  ・" },
	["KEYCODE_M"] = { ":keyboard:x68k:LINE6", "M  も" },
	["KEYCODE_DEL"] = { ":keyboard:x68k:LINE6", "DEL" },
	-- :keyboard:x68k:LINE7
	["KEYCODE_PGUP"] = { ":keyboard:x68k:LINE7", "ROLL UP" },
	["KEYCODE_RIGHT"] = { ":keyboard:x68k:LINE7", "Cursor Right" },
	["KEYCODE_END"] = { ":keyboard:x68k:LINE7", "UNDO" },
	["KEYCODE_LEFT"] = { ":keyboard:x68k:LINE7", "Cursor Left" },
	["KEYCODE_NUMLOCK"] = { ":keyboard:x68k:LINE7", "Tenkey CLR" },
	["KEYCODE_UP"] = { ":keyboard:x68k:LINE7", "Cursor Up" },
	["KEYCODE_DOWN"] = { ":keyboard:x68k:LINE7", "Cursor Down" },
	["KEYCODE_PGDN"] = { ":keyboard:x68k:LINE7", "ROLL DOWN" },
	-- :keyboard:x68k:LINE8
	["KEYCODE_9PAD"] = { ":keyboard:x68k:LINE8", "Tenkey 9" },
	["KEYCODE_4PAD"] = { ":keyboard:x68k:LINE8", "Tenkey 4" },
	["KEYCODE_MINUSPAD"] = { ":keyboard:x68k:LINE8", "Tenkey -" },
	["KEYCODE_PLUSPAD"] = { ":keyboard:x68k:LINE8", "Tenkey +" },
	["KEYCODE_8PAD"] = { ":keyboard:x68k:LINE8", "Tenkey 8" },
	["KEYCODE_SLASHPAD"] = { ":keyboard:x68k:LINE8", "Tenkey /" },
	["KEYCODE_7PAD"] = { ":keyboard:x68k:LINE8", "Tenkey 7" },
	["KEYCODE_ASTERISK"] = { ":keyboard:x68k:LINE8", "Tenkey *" },
	-- :keyboard:x68k:LINE9
	["KEYCODE_ENTERPAD"] = { ":keyboard:x68k:LINE9", "Tenkey ENTER" },
	["KEYCODE_6PAD"] = { ":keyboard:x68k:LINE9", "Tenkey 6" },
	["KEYCODE_1PAD"] = { ":keyboard:x68k:LINE9", "Tenkey 1" },
	["KEYCODE_2PAD"] = { ":keyboard:x68k:LINE9", "Tenkey 2" },
	["KEYCODE_0PAD"] = { ":keyboard:x68k:LINE9", "Tenkey 0" },
	["KEYCODE_3PAD"] = { ":keyboard:x68k:LINE9", "Tenkey 3" },
	["KEYCODE_5PAD"] = { ":keyboard:x68k:LINE9", "Tenkey 5" },
	-- :keyboard:x68k:LINEA
	["KEYCODE_F12"] = { ":keyboard:x68k:LINEA", "XF2" },
	["KEYCODE_DELPAD"] = { ":keyboard:x68k:LINEA", "Tenkey ." },
	["KEYCODE_F11"] = { ":keyboard:x68k:LINEA", "XF1" },
	-- :keyboard:x68k:LINEB
	["KEYCODE_LALT"] = { ":keyboard:x68k:LINEB", "ひらがな (Hiragana)" },
	["KEYCODE_CAPSLOCK"] = { ":keyboard:x68k:LINEB", "CAPS" },
	["KEYCODE_RALT"] = { ":keyboard:x68k:LINEB", "XF5" },
	["KEYCODE_INSERT"] = { ":keyboard:x68k:LINEB", "INS" },
	-- :keyboard:x68k:LINEC
	["KEYCODE_F2"] = { ":keyboard:x68k:LINEC", "F2" },
	["KEYCODE_F1"] = { ":keyboard:x68k:LINEC", "F1" },
	["KEYCODE_RCONTROL"] = { ":keyboard:x68k:LINEC", "全角 (Fullwidth)" },
	["KEYCODE_F5"] = { ":keyboard:x68k:LINEC", "F5" },
	["KEYCODE_F3"] = { ":keyboard:x68k:LINEC", "F3" },
	["KEYCODE_F4"] = { ":keyboard:x68k:LINEC", "F4" },
	-- :keyboard:x68k:LINED
	["KEYCODE_F8"] = { ":keyboard:x68k:LINED", "F8" },
	["KEYCODE_F7"] = { ":keyboard:x68k:LINED", "F7" },
	["KEYCODE_F9"] = { ":keyboard:x68k:LINED", "F9" },
	["KEYCODE_F6"] = { ":keyboard:x68k:LINED", "F6" },
	["KEYCODE_F10"] = { ":keyboard:x68k:LINED", "F10" },
	-- :keyboard:x68k:LINEE
	["KEYCODE_LSHIFT"] = { ":keyboard:x68k:LINEE", "SHIFT" },
	["KEYCODE_RSHIFT"] = { ":keyboard:x68k:LINEE", "SHIFT" },
	["KEYCODE_PAUSE"] = { ":keyboard:x68k:LINEE", "OPT.2" },
	["KEYCODE_PRTSCR"] = { ":keyboard:x68k:LINEE", "OPT.1" },
	["KEYCODE_LCONTROL"] = { ":keyboard:x68k:LINEE", "CTRL" },
	-- :mouse_port:x68k:BTN
	["MOUSECODE_1_BUTTON2"] = { ":mouse_port:x68k:BTN", "P3 Button 2" },
	["MOUSECODE_1_BUTTON1"] = { ":mouse_port:x68k:BTN", "P3 Button 1" },
	-- :mouse_port:x68k:X
	["MOUSECODE_3_UNKNOWN_RELATIVE"] = { ":mouse_port:x68k:X", "Mouse X 3" },
	-- :mouse_port:x68k:Y
	["MOUSECODE_3_UNKNOWN_RELATIVE"] = { ":mouse_port:x68k:Y", "Mouse Y 3" },
	-- :options
}

