-- https://github.com/mamedev/mame/blob/master/src/devices/bus/pc_kbd/msnat.cpp

-- for k, v in pairs(manager.machine.ioport.ports[":kbd:ms_naturl:P1.2"].fields) do print(k) end
portmap = {
    -- P2.0
    ["Y"] = { ":kbd:ms_naturl:P2.0", "Y" },
    ["H"] = { ":kbd:ms_naturl:P2.0", "H" },
    ["J"] = { ":kbd:ms_naturl:P2.0", "J" },
    ["N"] = { ":kbd:ms_naturl:P2.0", "N" },
    ["M"] = { ":kbd:ms_naturl:P2.0", "M" },
    ["U"] = { ":kbd:ms_naturl:P2.0", "U" },
    ["6"] = { ":kbd:ms_naturl:P2.0", "6" },
    ["7"] = { ":kbd:ms_naturl:P2.0", "7" },
    -- P2.1
    ["ENTER"] = { ":kbd:ms_naturl:P2.1", "Enter" },
    ["CLOSEBRACE"] = { ":kbd:ms_naturl:P2.1", "\\" },
    ["BACKSLASH"] = { ":kbd:ms_naturl:P2.1", "]" },
    ["LEFT"] = { ":kbd:ms_naturl:P2.1", "Cursor Left" },
    ["BACKSPACE"] = { ":kbd:ms_naturl:P2.1", "Backspace" },
    ["F5"] = { ":kbd:ms_naturl:P2.1", "F5" },
    ["F6"] = { ":kbd:ms_naturl:P2.1", "F6" },
    ["EQUALS"] = { ":kbd:ms_naturl:P2.1", "=" },
    -- P2.2
    ["9"] = { ":kbd:ms_naturl:P2.2", "9" },
    ["0"] = { ":kbd:ms_naturl:P2.2", "0" },
    ["OPENBRACE"] = { ":kbd:ms_naturl:P2.2", "[" },
    ["L"] = { ":kbd:ms_naturl:P2.2", "L" },
    ["STOP"] = { ":kbd:ms_naturl:P2.2", "." },
    ["MINUS"] = { ":kbd:ms_naturl:P2.2", "-" },
    ["F7"] = { ":kbd:ms_naturl:P2.2", "F7" },
    ["F8"] = { ":kbd:ms_naturl:P2.2", "F8" },
    -- P2.3
    ["0"] = { ":kbd:ms_naturl:P2.3", "0" },
    ["COLON"] = { ":kbd:ms_naturl:P2.3", ";" },
    ["QUOTE"] = { ":kbd:ms_naturl:P2.3", "'" },
    ["SLASH"] = { ":kbd:ms_naturl:P2.3", "/" },
    ["DOWN"] = { ":kbd:ms_naturl:P2.3", "Cursor Down" },
    ["P"] = { ":kbd:ms_naturl:P2.3", "P" },
    ["F9"] = { ":kbd:ms_naturl:P2.3", "F9" },
    ["F10"] = { ":kbd:ms_naturl:P2.3", "F10" },
    -- P2.4
    ["UP"] = { ":kbd:ms_naturl:P2.4", "Cursor Up" },
    ["RWIN"] = { ":kbd:ms_naturl:P2.4", "Right Win" },
    ["RIGHT"] = { ":kbd:ms_naturl:P2.4", "Cursor Right" },
    ["SPACE"] = { ":kbd:ms_naturl:P2.4", "Space" },
    -- P2.5
    ["HOME"] = { ":kbd:ms_naturl:P2.5", "Home" },
    ["8_PAD"] = { ":kbd:ms_naturl:P2.5", "Keypad 8" },
    ["5_PAD"] = { ":kbd:ms_naturl:P2.5", "Keypad 5" },
    ["2_PAD"] = { ":kbd:ms_naturl:P2.5", "Keypad 2" },
    ["0_PAD"] = { ":kbd:ms_naturl:P2.5", "Keypad 0" },
    ["END"] = { ":kbd:ms_naturl:P2.5", "End" },
    ["F11"] = { ":kbd:ms_naturl:P2.5", "F11" },
    ["F12"] = { ":kbd:ms_naturl:P2.5", "F12" },
    -- P2.6
    ["INSERT"] = { ":kbd:ms_naturl:P2.6", "Insert" },
    ["DEL"] = { ":kbd:ms_naturl:P2.6", "Delete" },
    ["6_PAD"] = { ":kbd:ms_naturl:P2.6", "Keypad 6" },
    ["3_PAD"] = { ":kbd:ms_naturl:P2.6", "Keypad 3" },
    --["??"] = { ":kbd:ms_naturl:P2.6", "Keypad ." },
    ["9_PAD"] = { ":kbd:ms_naturl:P2.6", "Keypad 9" },
    ["F3"] = { ":kbd:ms_naturl:P2.6", "F3" },
    ["F4"] = { ":kbd:ms_naturl:P2.6", "F4" },
    -- P2.7
    ["SLASH"] = { ":kbd:ms_naturl:P2.7", "Keypad /" },
    ["7_PAD"] = { ":kbd:ms_naturl:P2.7", "Keypad 7" },
    ["4_PAD"] = { ":kbd:ms_naturl:P2.7", "Keypad 4" },
    ["PLUS_PAD"] = { ":kbd:ms_naturl:P2.7", "Keypad +" },
    ["1_PAD"] = { ":kbd:ms_naturl:P2.7", "Keypad 1" },
    ["ASTERIX"] = { ":kbd:ms_naturl:P2.7", "Keypad *" },
    ["PRTSCR"] = { ":kbd:ms_naturl:P2.7", "Print Screen" },
    ["MENU"] = { ":kbd:ms_naturl:P2.7", "Menu" },
    -- P1.0
    ["LWIN"] = { ":kbd:ms_naturl:P1.0", "Left Win" },
    ["SCRLOCK"] = { ":kbd:ms_naturl:P1.0", "Scroll Lock" },
    ["ENTER_PAD"] = { ":kbd:ms_naturl:P1.0", "Keypad Enter" },
    -- P1.1
    ["LCONTROL"] = { ":kbd:ms_naturl:P1.1", "Left Ctrl" },
    ["RCONTROL"] = { ":kbd:ms_naturl:P1.1", "Right Ctrl" },
    ["CAPSLOCK"] = { ":kbd:ms_naturl:P1.1", "Caps Lock" },
    -- P1.2
    ["PGUP"] = { ":kbd:ms_naturl:P1.2", "Page Up" },
    ["2"] = { ":kbd:ms_naturl:P1.2", "2" },
    ["W"] = { ":kbd:ms_naturl:P1.2", "W" },
    ["S"] = { ":kbd:ms_naturl:P1.2", "S" },
    ["X"] = { ":kbd:ms_naturl:P1.2", "X" },
    ["PGDOWN"] = { ":kbd:ms_naturl:P1.2", "Page Down" },
    ["F1"] = { ":kbd:ms_naturl:P1.2", "F1" },
    ["F2"] = { ":kbd:ms_naturl:P1.2", "F2" },
    -- P1.3
    ["LALT"] = { ":kbd:ms_naturl:P1.3", "Left Alt" },
    ["RALT"] = { ":kbd:ms_naturl:P1.3", "Right Alt" },
    ["MINUS_PAD"] = { ":kbd:ms_naturl:P1.3", "Keypad -" },
    ["NUMLOCK"] = { ":kbd:ms_naturl:P1.3", "Num Lock" },
    -- P1.4
    ["I"] = { ":kbd:ms_naturl:P1.4", "I" },
    ["K"] = { ":kbd:ms_naturl:P1.4", "K" },
    ["D"] = { ":kbd:ms_naturl:P1.4", "D" },
    ["C"] = { ":kbd:ms_naturl:P1.4", "C" },
    ["COMMA"] = { ":kbd:ms_naturl:P1.4", "," },
    ["E"] = { ":kbd:ms_naturl:P1.4", "E" },
    ["3"] = { ":kbd:ms_naturl:P1.4", "3" },
    ["8"] = { ":kbd:ms_naturl:P1.4", "8" },
    -- P1.5
    ["5"] = { ":kbd:ms_naturl:P1.5", "5" },
    ["R"] = { ":kbd:ms_naturl:P1.5", "R" },
    ["F"] = { ":kbd:ms_naturl:P1.5", "F" },
    ["G"] = { ":kbd:ms_naturl:P1.5", "G" },
    ["V"] = { ":kbd:ms_naturl:P1.5", "V" },
    ["B"] = { ":kbd:ms_naturl:P1.5", "B" },
    ["T"] = { ":kbd:ms_naturl:P1.5", "T" },
    ["4"] = { ":kbd:ms_naturl:P1.5", "4" },
    -- P1.6
    ["ESC"] = { ":kbd:ms_naturl:P1.6", "Esc" },
    ["1"] = { ":kbd:ms_naturl:P1.6", "1" },
    ["Q"] = { ":kbd:ms_naturl:P1.6", "Q" },
    ["A"] = { ":kbd:ms_naturl:P1.6", "A" },
    ["Z"] = { ":kbd:ms_naturl:P1.6", "Z" },
    ["TAB"] = { ":kbd:ms_naturl:P1.6", "Tab" },
    ["TILDE"] = { ":kbd:ms_naturl:P1.6", "`" },
    -- P1.7
    ["LSHIFT"] = { ":kbd:ms_naturl:P1.6", "Left Shift" },
    ["RSHIFT"] = { ":kbd:ms_naturl:P1.6", "Right Shift" },
    ["CANCEL"] = { ":kbd:ms_naturl:P1.6", "Break" },
  }